quarkus-qe/quarkus-test-plans

README.md
Template for topics / bullet-points to be considered in test plan
=> Topics to be considered in test plan

QUARKUS-272.md
Quarkus Native support via Mandrel
@mjurc fyi, if you are around
=> Quarkus Native support via Mandrel

QUARKUS-270.md
Quarkus and OpenShift Serverless Serving
=> Quarkus and OpenShift Serverless Serving

QUARKUS-278.md
@rsvoboda this is the proposal test plan. I guess the next is to identify what scenarios will be out of scope for 7.6 testing.
=> Add test plan for QUARKUS-278: RH SSO 7.4

QUARKUS-640.md
QUARKUS-451 - Testing and verifying OpenShift Kafka with Quarkus
=> Add test plan for QUARKUS-451: Reactive Kafka

QUARKUS-553.md
Proposed TP for https://issues.redhat.com/browse/QUARKUS-553
=> Test plan for QUARKUS-553

QUARKUS-821.md
Plan for QUARKUS-821 - Early checks of code.quarkus as part of Acceptance pipeline
=> QUARKUS-821 Early checks of code.quarkus as part of Acceptance pipeline

QUARKUS-976.md
Effort for https://issues.redhat.com/browse/QUARKUS-976
=> Add test plan for HibernateORM Rest Data with Panache extension

QUARKUS-803.md
This is a very ambitious test plan. Please review and correct topics/statements that you find inappropriate.
=> Test plan for Red Hat Data Grid

QUARKUS-728.md
- Add missing JDK17 JEPs to test plan
=> Add JDK17 JEPs to Quarkus-728 test plan

QUARKUS-1266.md
Quarkus-1266 Support Kafka AVRO
=> Quarkus-1266 Support Kafka AVRO

QUARKUS-1255.md
QUARKUS-1255 Dev support for JaCoCo extension
=> QUARKUS-1255 Dev support for JaCoCo extension

QUARKUS-1079.md
Main issue https://issues.redhat.com/browse/QUARKUS-1079
=> Planned coverage of new features in Reactive Hibernate

QUARKUS-1520.md
QUARKUS-1520 - SmallRye Health codestart
=> QUARKUS-1520 - SmallRye Health codestart

QUARKUS-1504.md
QUARKUS-1504 - Update tools provided Dockerfiles to use RHEL 8.5
=> QUARKUS-1504 - Update tools provided Dockerfiles to use RHEL 8.5

QUARKUS-959.md
Apicurio devServices was promoted to product support
=> Add apicurio dev services as supported services

.idea/vcs.xml, .idea/workspace.xml, QUARKUS-728.md
Upgrade Quarkus-728 test plan according new Jenkins job spec
=> Upgrade JDK17 jenkins jobs references

QUARKUS-1070.md
* Adding a test plan for QUARKUS-1070 Composable Platform streams
and non-platform extension discovery.
=> QUARKUS-1070 Composable Platform

QUARKUS-1027.md
* Adding a test plan for QUARKUS-1027 OpenShift Service Binding - Tech
preview.
=> QUARKUS-1027 OpenShift Service Binding

QUARKUS-1405.md
Mutiny 1.x improvements, basically talks about `Mutiny context`. This PR is covering this `mutiny context` scenario
=> Quarkus-1405 / Mutiny 1.x improvements

QUARKUS-1061.md, QUARKUS-1075.md, QUARKUS-1164.md, QUARKUS-1223.md, QUARKUS-1408.md
https://issues.redhat.com/browse/QUARKUS-1408
Integration of the reactive MS SQL client with Dev Services.
Guides:
- https://quarkus.io/version/main/guides/datasource#reactive-datasource-2
- https://quarkus.io/version/main/guides/datasource#dev-services
- https://quarkus.io/version/main/guides/reactive-sql-clients
=> QUARKUS-1408 Dev Service for MS SQL Client

QUARKUS-1413.md
This test plan cover SmallRye Stork Quarkus integration (Technical Preview)
=> QUARKUS-1413 - Service Discovery with Stork

QUARKUS-1396.md
QUARKUS-1396 - Assisted updates
https://issues.redhat.com/browse/QUARKUS-1396
=> QUARKUS-1396 - Assisted updates

QUARKUS-1414.md
* Adding a test plan for QUARKUS-1414.
=> QUARKUS-1414 Service Binding improvement test plan

QUARKUS-1400.md
* Adding a test plan for Operator SDK product support (tech preview).
=> QUARKUS-1400 Operator SDK product support

QUARKUS-1153.md
QUARKUS-1153 - code.quarkus.redhat.com - allow user select a version
=> QUARKUS-1153 - code.quarkus.redhat.com - allow user select a version

QUARKUS-1251.md
* Adding a test plan for QUARKUS-1251.
=> Test plan for  RHBQ on OpenShift Dedicated

QUARKUS-1312.md
* Adding a test plan for QUARKUS-1312.
=> Test plan for performance testing integration

QUARKUS-1936.md
* Adding a test plan for QUARKUS-1936.
=> Test plan for Temurin certification

QUARKUS-1159.md
QUARKUS-1159 - Ensure Quarkus runs on a FIPS enabled RHEL 8 System
https://issues.redhat.com/browse/QUARKUS-1159
=> Add test plan for QUARKUS-1159

QUARKUS-732.md
The goal of this test plan is to cover improvements in configuration for managed Kafka on OpenShift
=> Test plans for QUARKUS-732

QUARKUS-2082.md
QUARKUS-2082 - Run more of the QE test suite upstream
=> QUARKUS-2082 - Run more of the QE test suite upstream

QUARKUS-2230.md
* Adding a test plan for QUARKUS-2230.
=> QUARKUS-2230 Introduce OpenShift based CI runs

QUARKUS-2282.md
* Adding a test plan for QUARKUS-2282.
=> QUARKUS-2282 Adjustable dependency check test plan

QUARKUS-2328.md, QUARKUS-2329.md, QUARKUS-2330.md
Relevant issues:
https://issues.redhat.com/browse/QUARKUS-2328
https://issues.redhat.com/browse/QUARKUS-2329
https://issues.redhat.com/browse/QUARKUS-2330
=> Describe test plans for coverage of Qute

QUARKUS-2388.md, QUARKUS-714.md
https://issues.redhat.com/browse/QUARKUS-2388
Promote Spring Data REST from TP to full support
Documentation: https://quarkus.io/version/main/guides/spring-data-rest
=> QUARKUS-2388 Promote Spring Data REST from TP to full support

QUARKUS-1737.md
Test plan for QUARKUS-1737 - Reactive and Distributed systems roadmap
=> QUARKUS-1737: Add test plans for reactive and distributed systems Fireball roadmap

QUARKUS-2389.md
QUARKUS-2389 - Promote OpenID Connect Client Filter Reactive from TP to full support
https://issues.redhat.com/browse/QUARKUS-2389
=> QUARKUS-2389 - Promote OpenID Connect Client Filter Reactive from TP to full support

QUARKUS-2387.md
QUARKUS-2387 - Promote Mailer extension from TP to full support
https://issues.redhat.com/browse/QUARKUS-2387
=> QUARKUS-2387 - Promote Mailer extension from TP to full support

QUARKUS-2392.md, QUARKUS-2393.md, QUARKUS-2395.md, QUARKUS-2396.md
Test plans for drop TP JIRAs
QUARKUS-2392 - Drop Tech Preview support for RESTEasy Mutiny
QUARKUS-2393 - Drop Tech Preview for Mutiny support for REST Client extension
QUARKUS-2395 - Drop TP from Security JPA extension
QUARKUS-2396 - Drop TP for Eclipse Vert.x GraphQL
=> Test plans for drop TP JIRAs

QUARKUS-2487.md
HTTP body compression on `quarkus-reactive-routes` and `quarkus-resteasy-reactive` extensions
=> Add QUARKUS-2487: Compression support for Reactive Routes and RESTEasy Reactive - Test plan

QUARKUS-2483.md
Adds a test plan for [QUARKUS-2483](https://issues.redhat.com/browse/QUARKUS-2483).
=> Add test plan for QUARKUS-2483

QUARKUS-2332.md
QUARKUS-2332 - Drop TP support for the Reactive DB2 client
=> QUARKUS-2332 - Drop TP support for the Reactive DB2 client

QUARKUS-2246.md
QUARKUS-2246 - Integrate Vertx HTTP extension with custom CredentialsProvider
https://issues.redhat.com/browse/QUARKUS-2246
=> QUARKUS-2246 - Integrate Vertx HTTP extension with custom CredentialsProvider

QUARKUS-2481.md
PR in order to create a test plan for custom JAXB context injection feature.
=> QUARKUS-2481: Allow to provide custom configuration for JAXB context

QUARKUS-2743.md
@rsvoboda I wrote this test plan and then realized it's a bug. We do not write test plans for bug, right? If it doesn't make sense to keep TP for bug, I'm going to close the PR on Friday.
=> Add test plan for QUARKUS-2743

QUARKUS-2491.md, QUARKUS-2743.md
Adds extra lines between test plans so that each link starts on the new line.
=> QUARKUS-2743 and QUARKUS-2491 - start links on new lines

QUARKUS-2744.md
Adds a test plan for https://issues.redhat.com/browse/QUARKUS-2744.
=> Add test plan for QUARKUS-2744

QUARKUS-2787.md
JIRA link: https://issues.redhat.com/browse/QUARKUS-2787
- https://quarkus.io/version/main/guides/rest-data-panache
- https://quarkus.io/version/main/guides/openapi-swaggerui
- https://quarkus.io/version/main/guides/spring-data-rest
=> QUARKUS-2787 Rest Data Panache: Correct Open API integration

.github/pull_request_template.md, README.md
Based on RHBQ 2.13 restrospective action items.
Adds reminders about possible related topics for each new feature:
- Existing README file.
- New pull request template.
=> Add full picture checks to README and PR template

QUARKUS-2829.md
JIRA: https://issues.redhat.com/browse/QUARKUS-2829
Quarkus documentation: https://quarkus.io/guides/vertx
Select all applicable areas that have been considered in this test plan:
=> Tests plans for Micrometer metrics inside managed Vert.X

QUARKUS-2492.md
JIRA: https://issues.redhat.com/browse/QUARKUS-2492
Quarkus documentation: https://www.narayana.io/
Select all applicable areas that have been considered in this test plan:
=> Add covered databases to transaction API test plan

.github/pull_request_template.md
PR template - considerable topics polish
Proposal
===========
JIRA:
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> PR template - considerable topics polish

QUARKUS-2492.md
JIRA: https://issues.redhat.com/browse/QUARKUS-2492
Quarkus documentation: https://quarkus.io/guides/transaction#reactive-extensions
The provided metrics are custom metrics handled by the application code.
Select all applicable areas that have been considered in this test plan:
=> Remove reactive coverage from Transaction API testPlan

QUARKUS-2738.md
JIRA: https://issues.redhat.com/browse/QUARKUS-2738
Quarkus documentation: Not available at the moment, see PR: https://github.com/quarkusio/quarkus/pull/30506/files
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Test plans for Management Interface

QUARKUS-2736.md
JIRA: https://issues.redhat.com/browse/QUARKUS-2736
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add a test plan for QUARKUS-2736

QUARKUS-2738.md
=> QUARKUS-2738 - fix typo

QUARKUS-2738.md
=> Fix typo in QUARKUS-2738 plan

QUARKUS-2991.md
JIRA: https://issues.redhat.com/browse/QUARKUS-2991
- https://quarkus.io/version/main/guides/opentelemetry
- https://quarkus.io/version/main/guides/openapi-swaggerui
- https://quarkus.io/version/main/guides/security-jwt
- https://quarkus.io/version/main/guides/smallrye-metrics
MicroProfile documentation:
- https://microprofile.io/2023/01/10/microprofile-6-0-release
- https://microprofile.io/2021/12/07/microprofile-5-0-release
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-2991 Support for MicroProfile 6

QUARKUS-3315.md
QUARKUS-3315 - Productise quarkus-jms-spi-deployment artifact
JIRA: https://issues.redhat.com/browse/QUARKUS-3315
Quarkus documentation: Not applicable
=> QUARKUS-3315 - Productise quarkus-jms-spi-deployment artifact

QUARKUS-1391.md
JIRA: https://issues.redhat.com/browse/QUARKUS-1391
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Test plan for podman

QUARKUS-2830.md
JIRA: https://issues.redhat.com/browse/QUARKUS-2830
- https://quarkus.io/guides/vertx
- https://quarkus.io/guides/vertx-reference
- https://quarkus.io/guides/reactive-event-bus
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Planned coverage for VertX-specific metrics

QUARKUS-3260.md
QUARKUS-3260 - Tech Preview support for elasticsearch rest client
JIRA: https://issues.redhat.com/browse/QUARKUS-3260
Quarkus documentation: https://quarkus.io/guides/elasticsearch
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-3260 - Tech Preview support for elasticsearch rest client

QUARKUS-874.md
JIRA: https://issues.redhat.com/browse/QUARKUS-874
Quarkus documentation: N/A
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Update test plan for QUARKUS-874

QQE-377.md
JIRA:
[QQE-376](http://issues.redhat.com/browse/QQE-376 )
[HTTP Reference ](https://quarkus.io/guides/http-reference#ssl)
[RestEasy Reactive guide](https://quarkus.io/guides/resteasy-reactive)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Test plan for QQE-377- HTTP/2 test use cases for Rest endpoints

QUARKUS-3466.md
JIRA: https://issues.redhat.com/browse/QUARKUS-3466
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add QUARKUS-3466 Test Plan

QUARKUS-3660.md, QUARKUS-4144.md
JIRA:
- https://issues.redhat.com/browse/QUARKUS-3660
- https://issues.redhat.com/browse/QUARKUS-4144
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Remove deprecated smallrye extensions

QUARKUS-2391.md
JIRA:
https://issues.redhat.com/browse/QUARKUS-2391 
[Opentelemetry-quickstart code](https://github.com/quarkusio/quarkus-quickstarts/tree/main/opentelemetry-quickstart)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Opentelemetry from TP to full supported

QUARKUS-2391.md
JIRA:
https://issues.redhat.com/browse/QUARKUS-2391
[Opentelemetry-quickstart code](https://github.com/quarkusio/quarkus-quickstarts/tree/main/opentelemetry-quickstart)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Update QUARKUS-2391.md with Otel in dev mode scenario

QUARKUS-4179.md, QUARKUS-4318.md
JIRA: https://issues.redhat.com/browse/QUARKUS-4179
Quarkus documentation: https://quarkus.io/guides/security-openid-connect-client-reference#token-propagation-reactive
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Test plans for https://issues.redhat.com/browse/QUARKUS-4179

QUARKUS-3225.md
JIRA: https://issues.redhat.com/browse/QUARKUS-3225
Quarkus documentation: ha ha
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-3225

QUARKUS-3461.md
Adding a test plan for QUARKUS-3461: verify behaviour and functionality of Quarkus CLI update command with RHBQ
JIRA:  https://issues.redhat.com/browse/QUARKUS-3461
https://quarkus.io/guides/update-quarkus
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Adding a test plan for QUARKUS-3461

QQE-833.md
JIRA: https://issues.redhat.com/browse/QQE-833
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Plans for container-image-podman extension

QUARKUS-4592.md
JIRA: https://issues.redhat.com/browse/QUARKUS-4592
Quarkus documentation: https://quarkus.io/version/main/guides/tls-registry-reference#lets-encrypt
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-4592

QUARKUS-4120.md
JIRA: https://issues.redhat.com/browse/QUARKUS-4120
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-4120

QUARKUS-4958.md
JIRA: https://issues.redhat.com/browse/QUARKUS-4958
Quarkus documentation: https://quarkus.io/guides/spring-data-jpa
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-4958

QUARKUS-4221.md
JIRA: https://issues.redhat.com/browse/QUARKUS-4221
PR: https://github.com/quarkus-qe/quarkus-test-suite/pull/2003
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add TP for QUARKUS-4221 Productization of quarkus-picocli extension

QUARKUS-4221.md
JIRA: https://issues.redhat.com/browse/QUARKUS-4221
PR: https://github.com/quarkus-qe/quarkus-test-suite/pull/2043
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Enable tests to be executed with native mode

QQE-1290.md
JIRA: https://issues.redhat.com/browse/QQE-1290
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QQE-1290

.github/pull_request_template.md, README.md
Template and README update: Check the community status of the extension/feature
JIRA: N/A
Quarkus documentation: N/A
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Check the community status of the extension/feature

QUARKUS-5613.md
JIRA:  https://issues.redhat.com/browse/QUARKUS-5613
PR GH:  https://github.com/quarkusio/quarkus/pull/43283
- [security-openid-connect-client-reference](https://quarkus.io/guides/security-openid-connect-client-reference)
- [security-oidc-code-flow-authentication](https://quarkus.io/guides/security-oidc-code-flow-authentication)
- [security-openid-connect-client-registration](https://quarkus.io/guides/security-openid-connect-client-registration)
Extension/feature community status:
- quarkus-oidc (stable/supported)
- quarkus-oidc-client(stable/supported)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add TP for QUARKUS-5613 OIDC Response filter mechanism

QUARKUS-4573.md
JIRA: https://issues.redhat.com/browse/QUARKUS-4573
Quarkus documentation: https://quarkus.io/version/main/guides/quarkus-runtime-base-image
Extension/feature community status: stable
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add QUARKUS-4573 test plan

QUARKUS-5656.md
QUARKUS-5656 OTel metrics for Microprofile Telemetry 2.0
Quarkus documentation: https://quarkus.io/guides/opentelemetry-metrics
Extension/feature community status: full community support https://code.quarkus.io/?extension-search=openteleme
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-5656 OTel metrics for Microprofile Telemetry 2.0

QUARKUS-5615.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5615
Quarkus documentation: https://quarkus.io/guides/rest#reflection-free-jackson-serialization
Extension/feature community status: Technology Preview
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-5615 Add test plans for reflection-free (de)serialization

QUARKUS-5666.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5666 
https://quarkus.io/guides/tls-registry-reference
Extension/feature community status: technology preview
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add TP for QUARKUS-5666.md Add support for encrypted PKCS#8 - technology preview

QUARKUS-5666.md
This is just a tweak of the TP https://github.com/quarkus-qe/quarkus-test-plans/pull/198/files 
JIRA: https://issues.redhat.com/browse/QUARKUS-5666
=> Adding not that we are not testing with FIPS-enable environment

QUARKUS-5656.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5656
Be more explicit about MicroProfile Telemetry 2.0 TCK
Update of existing TP
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-5656 - be more explicit about MicroProfile Telemetry 2.0 TCK

QUARKUS-5654.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5654
Quarkus documentation:  https://quarkus.io/guides/rest-client
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Tests plans for update of MP REST Client to 4.0

QUARKUS-5186.md
=> Fix QUARKUS-5186 headline

QUARKUS-5477.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5477
Quarkus documentation: https://quarkus.io/guides/security-openid-connect-client-reference#oidc-client-spi
Extension/feature community status: Part of the supported `quarkus-oidc-client`
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-5477

QUARKUS-5614
JIRA: https://issues.redhat.com/browse/QUARKUS-5614
Quarkus documentation: https://quarkus.io/guides/security-authorize-web-endpoints-reference
Test coverage: https://github.com/quarkus-qe/quarkus-test-suite/pull/2387
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-5614

QUARKUS-5617.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5617
Quarkus documentation: https://quarkus.io/guides/security-authentication-mechanisms#combining-authentication-mechanisms
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-5617

QUARKUS-5655.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5655
Quarkus documentation: https://quarkus.io/guides/security-authorize-web-endpoints-reference#permission-checker
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-5655

QUARKUS-5471.MD
JIRA: https://issues.redhat.com/browse/QUARKUS-5471
Quarkus documentation: nope
Extension/feature community status: nope
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add QUARKUS-5471 test plan

QUARKUS-5658.md
* Updating the test plan to account for implementation realities.
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-5658 test plan update

QUARKUS-5664.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5664
Quarkus documentation: https://quarkus.io/guides/tls-registry-reference
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Policy configuration for invalid certificates

QUARKUS-5662.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5662
Quarkus documentation:  https://quarkus.io/guides/security-oidc-code-flow-authentication#using-the-authorization-code-flow-mechanism ,  https://quarkus.io/guides/security-openid-connect-client-reference#jwt-bearer
Extension/feature community status: SUPPORTED
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add TP for QUARKUS-5662

QUARKUS-5664.md
follow-up to https://github.com/quarkus-qe/quarkus-test-plans/pull/226/files
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Fix an error in the test plan

QUARKUS-5653.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5653
Quarkus documentation: https://quarkus.io/guides/security-oidc-code-flow-authentication#oidc-token-revocation
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-5653

QQE-674.md
It's just a title correction to the specific TP --> https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QQE-674.md
=> Correction of the title for QQE-674.md

QUARKUS-5653.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5653
Quarkus documentation: https://quarkus.io/guides/security-oidc-code-flow-authentication#oidc-token-revocation
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-5653 Test plan update - testing limitations

QUARKUS-5661.md
JIRA: https://issues.redhat.com/browse/QUARKUS-5661
Quarkus documentation: https://quarkus.io/guides/kubernetes-client#optimizing-native-image
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plans for kubernetes-client bump

QUARKUS-6244.MD
JIRA: https://issues.redhat.com/browse/QUARKUS-6244
Quarkus documentation: https://quarkus.io/guides/hibernate-orm#jakarta-data-2
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add a test plan for QUARKUS-6244

QUARKUS-6257.md
JIRA: https://issues.redhat.com/browse/QQE-1584
Quarkus documentation: https://quarkus.io/blog/quarkus-meets-langchain4j/
Extension/feature community status: in quarkiverse
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add strategy for LangChain4J coverage

QUARKUS-6241.MD
JIRA: https://issues.redhat.com/browse/QUARKUS-6241
Quarkus documentation: https://quarkus.io/guides/hibernate-reactive#orm-and-reactive-extension-simultaneously
Extension/feature community status: Hibernate ORM supported, Hibernate Reactive preview so preview on average
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-6241

QUARKUS-6258.md
JIRA: https://issues.redhat.com/browse/QUARKUS-6258
Quarkus documentation: https://quarkus.io/blog/quarkus-meets-langchain4j/
Extension/feature community status: preview
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-6258 | Quarkus AI - phase 1 features

QUARKUS-5867.MD
JIRA: https://issues.redhat.com/browse/QUARKUS-5867
Quarkus documentation: https://quarkus.io/guides/telemetry-micrometer-to-opentelemetry
Extension/feature community status: preview
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add QUARKUS-5867 test plan

QUARKUS-6262.MD
JIRA: https://issues.redhat.com/browse/QUARKUS-6262
Quarkus documentation: https://quarkus.io/guides/validation
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-6262

QUARKUS-6551.md
I typed wrong JIRA number in original PR https://github.com/quarkus-qe/quarkus-test-plans/pull/263 - Fixing this to correct one 6551.
JIRA: https://issues.redhat.com/browse/QUARKUS-6551
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> QUARKUS-6551 - fix JIRA number

QUARKUS-6550.md
JIRA: https://issues.redhat.com/browse/QUARKUS-6550
Upstream issues: https://github.com/quarkusio/quarkus/issues/40258 https://github.com/quarkusio/quarkus/issues/49041
Upstream PR: https://github.com/quarkusio/quarkus/pull/49042
Quarkus documentation: see the references mentioned in this PR
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-6550 - Support for customizing request and response body in OIDC filters

QUARKUS-6474.md
JIRA: https://issues.redhat.com/browse/QUARKUS-6474
Quarkus documentation: https://quarkus.io/guides/security-openid-connect-client-reference#refresh-access-tokens
Extension/feature community status: full-support
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute
=> Add test plan for QUARKUS-6474 - OIDC Client: Add periodic asynchronous tokens refresh for performance critical applications
