quarkus-qe/quarkus-test-plans

QUARKUS-167.md

Proposed TP for https://github.com/quarkus-qe/quarkus-openshift-test-suite/issues/167
Jira ref: https://issues.redhat.com/browse/QUARKUS-190

Add test plan for QUARKUS-190: Vertx - sql

---

QUARKUS-960.md

- Update `Create extensions` item to `List extensions` as it's not possible to create extensions via the CLI, but listing them.
- Add item to verify the boot times comparison.

Update test plan for QUARKUS-960

---

QUARKUS-959.md

Dev Service simplifies testing and Quarkus dev-mode with containers.
As a developer, you spend too much time in unproductive cycles such us:
```
Write Code → Compile → Deploy → Refresh Browser → Repeat
```
But Quarkus allow you to pick up your changes on the fly thanks to Quarkus dev-mode, and also allows you to deploy some developer services such as BDs or Kafka with almost zero configuration thanks to dev-services. 
Quarkus Dev-mode developer cycle:
```
Write Code → Refresh Browser → Repeat
```
Note: all your service DBs will be deployed and refresh it on the fly, allowing you to develop your services following a continuous testing approach. 
This PR is a test plan to cover the supported features scoped for RHBQ 2.2 related to Dev-services

Add Test plan for Quarkus-959

---

QUARKUS-959.md

Add to DevService test plan the following verifications:
- quarkus.kafka.devservices.enabled:  Kafka dev services is enabled by default unless kafka.bootstrap.servers is set or if all the Reactive Messaging Kafka channel are configured with a bootstrap.servers
- quarkus.datasource.devservices.enabled: datasource dev services is enabled by default unless there is an existing configuration present
- quarkus.datasource.devservices.port (Optional)

Add DevServices properties to test plan Quarkus-959

---

QUARKUS-728.md

As a part of Java 17 release that will happen in September, we have released this test plan in order to verify the integration between OpenJDK 17 and Quarkus 2.x

Add test plan for Quarkus-728

---

QUARKUS-1079.md

Test plans for Hibernate Reactive and Hibernate Reactive Panache modules, both (as of v2.0.0)currently in Tech Preview status. Part of wider https://issues.redhat.com/browse/QUARKUS-962 and https://issues.redhat.com/browse/QUARKUS-1079 issues

Plans for Hibernate Reactive tests

---

QUARKUS-640.md

Missing a reference to apicurio serdes as a part of the testing scope

Upgrade Quarkus-640 - Apicurio serdes

---

README.md

Sometimes a test plan is directly linked to other test plans. In those cases, we have created a new section called "Related test plans" where you can link your test plan with the related ones.

Add  "Related test plans" subject to README.md

---

QUARKUS-1397.md
QUARKUS-728.md

JDK 17 is going to be tech-preview supported in the next product release. This PR adds some amends to the existing JDK17 test plan.

Update JDK17 / Quarkus-728 test plan

---

QUARKUS-1223.md

https://issues.redhat.com/browse/QUARKUS-1223
Test plan for Hibernate Search feature provided by `hibernate-search-orm-elasticsearch` extension.
Guide: https://quarkus.io/guides/hibernate-search-orm-elasticsearch

QUARKUS-1223 Hibernate Search product support

---

QUARKUS-1404.md

Quarkus / Vertx has been upgraded to 4.2.2. This PR will cover all the additional verification to the existing test coverage that needs to be added.

Quarkus-1404 Vert.x update to 4.2.x or 4.3.x

---

QUARKUS-1397.md
QUARKUS-1409.md

- QUARKUS-1409: This test plan talks about cloudevents integration into AMQP connector
- Quarkus-1397 -> QUARKUS-1397 (Fix typo)

QUARKUS-1409 - Add Cloud Events support to the AMQP connector

---

QUARKUS-1223.md

- Reactive Resteasy test development was removed from the test plan, because currently there is an open issue that need to be fixed.
- Outbox polling is already well covered in upstream
- Postgresql and Mysql was selected as supported databases in order to verify schemas and databases multi-tenant implementation support

Update Quarkus-1223 / Hibernate Search product support

---

QUARKUS-1472.md

Our tooling should support detecting and/or allowing users to select which Java version to use.
This test plan covers the first part: "support detecting java version"

Add java version support tooling test plan

---

QUARKUS-1490.md

QUARKUS-1490 Use BuildItem to enable use of TestContainers shared network

QUARKUS-1490 Use BuildItem to enable use of TestContainers shared network

---

QUARKUS-2019.md

QUARKUS-2019 - Tech preview support for resteasy-reactive-jaxb
https://issues.redhat.com/browse/QUARKUS-2019

QUARKUS-2019 - Tech preview support for resteasy-reactive-jaxb

---

QUARKUS-1676.md

Provides a test plan for [QUARKUS-1676](https://issues.redhat.com/browse/QUARKUS-1676)

QUARKUS-1676 mTLS with OIDC Server

---

QUARKUS-2148.md

This PR adds a test plan for [QUARKUS-2148](https://issues.redhat.com/browse/QUARKUS-2148).

Add a test plan for QUARKUS-2148

---

QUARKUS-1159.md

Add FIPS vs non-FIPS coverage 
```
- Date 29/07/2022
FIPS total amount of test:     1,830 tests
Non-FIPS total amount of test: 2,276 tests
```

Update FIPS support test plan

---

QUARKUS-1159.md

- Fix wrong Quarkus version used on the verification

Fix typo on QUARKUS-1769 test plan

---

QUARKUS-1325.md

Quarkus Helm chart test-plan
- Generate and deploy a Quarkus Helm Chart over Openshift default repository
- Update a deployed chart with a new Quarkus application chart version
- Verify some mapping between Quarkus configuration and generated Helm chart:
- Quarkus SmallRye Health

Add QUARKUS-1325 - Helm chart support for Quarkus

---

QUARKUS-2284.md

Adds a test plan for [QUARKUS-2284](https://issues.redhat.com/browse/QUARKUS-2284).

QUARKUS 2284 - Support using OpenShift Serverless Functions

---

QUARKUS-2390.md

https://issues.redhat.com/browse/QUARKUS-2390
Documentation: https://quarkus.io/version/main/guides/rest-data-panache

QUARKUS-2390 Promote quarkus-hibernate-orm-rest-data-panache extension from TP to full support

---

QUARKUS-2284.md

Updates QUARKUS-2284 test plan now that I have more experience with Quarkus Knative Eventing.

Update QUARKUS-2284 test plan

---

QUARKUS-2394.md

Opentelemetry Jaeger exported has been deprecated from an official Quarkus support point of view. The extension `quarkus-opentelemetry-exporter-jaeger` will be moved to Quarkiverse and `quarkus-opentelemetry-exporter-otlp` extension has been promoted as the supported one.

Add Quarkus-2394: Drop OpenTelemetry Jaeger exporter

---

QUARKUS-2489.md

Backchannel logout applies to `quarkus-oidc` and basically is a standard way to do logout in to a single sign-on service.
We will use Keycloak as an OIDC provider and the flavor of the extensions (classic or reactive) is not relevant for this coverage.

QUARKUS-2489: Add logout flow on OIDC

---

QUARKUS-2485.md

https://issues.redhat.com/browse/QUARKUS-2485
Test plan focused on missing coverage of the `smallrye-graphql` extension, with regards to the newly supported non-blocking execution model.

QUARKUS-2485 SmallRye GraphQL non-blocking support

---

QUARKUS-2490.md

https://issues.redhat.com/browse/QUARKUS-2490
Enhancement of the basic `vertx-http` functionality of user-defined response headers: makes possible to define custom headers for multiple path at once (i.e. in one group of configuration properties).
See also: https://quarkus.io/guides/http-reference#additional-http-headers-per-path.
The TP suggests extending the already existing test coverage by running the tests in multiple modes and environments.

QUARKUS-2490 Add HTTP headers for specific paths

---

QUARKUS-2453.md
QUARKUS-2527.md

QUARKUS-2453 / QUARKUS-2527 - Deprecate quarkus-reactive-routes extension
- https://issues.redhat.com/browse/QUARKUS-2453 - Deprecate quarkus-reactive-routes extension
- https://issues.redhat.com/browse/QUARKUS-2527 - Add support for deprecated label to code.quarkus.redhat.com

QUARKUS-2453 / QUARKUS-2527 - Deprecate quarkus-reactive-routes extension

---

QUARKUS-2349.md

We are not going to cover Quarkus app over JDK11 in native mode. All coverage is going to be done over JDK 17. This commit remove a partial statement that could be misunderstood.

Fix QUARKUS-2349: Fully support Java 17 and drop Java 11 for Native application

---

QUARKUS-2394.md

Extensions `quarkus-opentelemetry-exporter-jaeger` and `quarkus-opentelemetry-exporter-otlp` are going to be replaced by `quarkus-opentelemetry`.

Quarkus-2394: drop quarkus-opentelemetry-exporter-otlp extension. Replaced by quarkus-opentelemetry

---

QUARKUS-2524.md

QUARKUS-2524 - Make the list of productized dependencies a part of product testing deliverables
JIRA link: https://issues.redhat.com/browse/QUARKUS-2524
Delivered file is internal detail, thus we do not need to describe the TP in more details

QUARKUS-2524 - Make the list of productized dependencies a part of product testing deliverables

---

QUARKUS-2480.md

Testplan:
Hibernate `@SearchExtension` annotation allows you to customize your Hibernate/Elasticsearch index configuration

QUARKUS-2480: Introduce @SearchExtension to configure Hibernate Search through annotated beans

---

QUARKUS-2790.md

Adds a test plan for QUARKUS-2790. I've wrote down test results here https://issues.redhat.com/browse/QUARKUS-2790.

Add a test plan for QUARKUS-2790

---

QUARKUS-2788.md

Also covers QUARKUS-2786 Propagate the javax.annotation.security annotations in REST Data.
JIRA links:
- https://issues.redhat.com/browse/QUARKUS-2788
- https://issues.redhat.com/browse/QUARKUS-2786
- https://quarkus.io/version/main/guides/rest-data-panache
- https://quarkus.io/version/main/guides/security-overview-concept
- https://quarkus.io/version/main/guides/spring-data-rest

QUARKUS-2788 Support setting the RolesAllowed in the Panache REST Data extension

---

QUARKUS-2492.md

Programmatic distributed JDBC transaction API based on Narayana library

Add QUARKUS-2492: Transaction API

---

QUARKUS-2812.md

Add information about dev-mode prompt which enables users to activate the feature.
JIRA: https://issues.redhat.com/browse/QUARKUS-2812
Quarkus documentation: https://quarkus.io/guides/build-analytics
PR: https://github.com/quarkusio/quarkus/pull/33555
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Amend QUARKUS-2812 test plan

---

QUARKUS-3535.md

JIRA: https://issues.redhat.com/browse/QUARKUS-3535
Quarkus documentation: https://quarkus.io/guides/all-config#quarkus-core_quarkus.thread-pool.queue-size
Native mode assumptions go down to the https://quarkus.io/guides/native-reference#multi-thread and the fact that I didn't really manage to reproduce it in native mode. Maybe it is safe to say that if I can't reproduce it here https://github.com/quarkus-qe/quarkus-test-suite/pull/1551 then users are less likely to be affected by any related issue.
I realize that Keycloak team had issues in OpenShift, but that really goes down to where big load happens, so it is not important whether you run this test on baremetal or OpenShift as there is no relevance of these changes to cloud environment.
- Logging
- Tracing
- Metrics
- Security
- …

Add test plan for QUARKUS-3535

---

QUARKUS-658.md

JIRA: [QUARKUS-658](https://issues.redhat.com/browse/QUARKUS-658)
Quarkus documentation: [HTTP/2 Support](https://quarkus.io/guides/rest-client-reactive#http2-support)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for QUARKUS-658 - Reactive REST client - support HTTP/2

---

QUARKUS-2994.md

JIRA: https://issues.redhat.com/browse/QUARKUS-2994
Quarkus documentation: https://quarkus.io/blog/quarkus-3-5-0-released/
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-2994|JDK 21 support

---

QUARKUS-3007.md

* Adding a test plan for QUARKUS-3007: Aarch64/ARM Support for both native and JVM Quarkus apps
JIRA: https://issues.redhat.com/browse/QUARKUS-3007
Quarkus documentation: https://access.redhat.com/articles/4966181
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Adding a test plan for QUARKUS-3007

---

QUARKUS-2994.md

JIRA: [QUARKUS-2994](https://issues.redhat.com/browse/QUARKUS-2994)
Fix for https://github.com/quarkus-qe/quarkus-test-plans/pull/155
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-2994 | Clear out test plans in regards to baremetal jobs

---

QUARKUS-3007.md

JIRA: https://issues.redhat.com/browse/QUARKUS-3007
* Adding some starting estimates for what the times required for certification of release on aarch64 may be like.
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Estimation of total time impact for aarch64

---

QQE-343.md

JIRA:
[Quarkus and non JSON payload in REST endpoints](https://issues.redhat.com/browse/QQE-343)
Quarkus documentation: 
[Resteasy-reactive#xml-serialisation](https://quarkus.io/guides/resteasy-reactive#xml-serialisation)
[Reactive-jax-rs-resources guide](https://quarkus.io/guides/getting-started-reactive#reactive-jax-rs-resources )
[Resteasy-reactive#readers-and-writers-mapping-entities-and-http-bodies](https://quarkus.io/guides/resteasy-reactive#readers-and-writers-mapping-entities-and-http-bodies)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QQE-343 Quarkus and non JSON payload in REST endpoints

---

QUARKUS-2994.md

Previous PR: https://github.com/quarkus-qe/quarkus-test-plans/pull/155
Updates required, since default native image for RHBQ 3.8 is registry-proxy.engineering.redhat.com/rh-osbs/quarkus-mandrel-for-jdk-21-rhel8:23.1
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Run Native jobs on JDK 21 as well

---

QQE-378.md

Jira : [https://issues.redhat.com/browse/QQE-378](https://issues.redhat.com/browse/QQE-378)
- [Quarkus - http-reference#http-compression](https://quarkus.io/guides/http-reference#http-compression)
- [Quarkus - reactive-routes#http-compressio](https://quarkus.io/guides/reactive-routes#http-compression)
- [Vert.x - http_compression](https://vertx.io/docs/vertx-core/java/#_http_compression )
- [Vert.x - Handling compressed body](https://vertx.io/docs/vertx-core/java/#_handling_compressed_body)
- [Vert.x - http_compression_algorithms](https://vertx.io/docs/vertx-core/java/#_http_compression_algorithms)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QQE 378 HTTP module / REST use-cases - Development topic compression Brotli4j

---

QUARKUS-3866.md

Adding a test plan for QUARKUS-3866: Dev support and productization for quarkus-security-jpa
JIRA: https://issues.redhat.com/browse/QUARKUS-3866
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Adding a test plan for QUARKUS-3866

---

QQE-378.md

Jira : https://issues.redhat.com/browse/QQE-378
[Quarkus - http-reference#http-compression](https://quarkus.io/guides/http-reference#http-compression)
[Quarkus - reactive-routes#http-compressio](https://quarkus.io/guides/reactive-routes#http-compression)
[Vert.x - http_compression](https://vertx.io/docs/vertx-core/java/#_http_compression)
[Vert.x - Handling compressed body](https://vertx.io/docs/vertx-core/java/#_handling_compressed_body)
[Vert.x - http_compression_algorithms](https://vertx.io/docs/vertx-core/java/#_http_compression_algorithms)
[Kafka-using-snappy-for-message-compression](https://quarkus.io/guides/kafka#using-snappy-for-message-compression)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add snappy compression test scenarios

---

QUARKUS-4550.md

JIRA: https://issues.redhat.com/browse/QUARKUS-4550
Quarkus documentation: https://quarkus.io/guides/all-config#quarkus-opentelemetry_quarkus-otel-exporter-otlp-traces-proxy-options-enabled
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add QUARKUS-4550 test plan

---

QUARKUS-4430.md

JIRA:
https://issues.redhat.com/browse/QUARKUS-4430
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for QUARKUS-4430 | http metrics should provide a path instead of REDIRECTION and NOT_FOUND

---

QUARKUS-3456.md

JIRA: https://issues.redhat.com/browse/QUARKUS-3456
Quarkus documentation: https://quarkus.io/version/main/guides/config-secrets#protect-the-keystore-password
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for QUARKUS-3456

---

QQE-379.md

JIRA:
[QQE-379](https://issues.redhat.com/browse/QQE-379)
- [Writing JSON REST Services ](https://quarkus.io/guides/rest-json)
- [Customizing the ObjectMapper in REST Client Jackson](https://quarkus.io/guides/rest-client#customizing-the-objectmapper-in-rest-client-jackson)
- [Creating the first JSON REST service](https://quarkus.io/guides/resteasy#creating-the-first-json-rest-service)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan of JSON payloads in Quarkus REST endpoints

---

QQE-379.md

After PR discussion and investigation that it's not possible to determine what library (quarkus-rest-jackson and quarkus-rest-jsonb) is used for serialization/deserialization , I've decided drop testing with quarkus-rest-jackson.
You can see also the comment here--> https://github.com/quarkus-qe/quarkus-test-plans/pull/179#discussion_r1680692118
JIRA:
[QQE-379](https://issues.redhat.com/browse/QQE-379)
[Writing JSON REST Services ](https://quarkus.io/guides/rest-json)
[Creating the first JSON REST service](https://quarkus.io/guides/resteasy#creating-the-first-json-rest-service)
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Refactor of QQE-379.md dropping Jackson approach

---

QQE-832.md

JIRA: https://issues.redhat.com/browse/QQE-832
Quarkus documentation: https://quarkus.io/guides/cache-infinispan-reference
Metrics are supported only for [Caffeine cache](https://quarkus.io/guides/cache#enabling-micrometer-metrics),  I tested it on simple app
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for QQE-832

---

QUARKUS-3007.md
QUARKUS-3446.md
QUARKUS-4942.md

* Updated QUARKUS-3007 to be more in line with what happened in 3.8
* Created followup test plan for OCP on aarch leftovers after 3.8 in QUARKUS-3446 test plan
* Created followup test plan for bare metal coverage in 3.15 in QUARKUS-4942 test plan
JIRA:
* https://issues.redhat.com/browse/QUARKUS-3007
* https://issues.redhat.com/browse/QUARKUS-3446
* https://issues.redhat.com/browse/QUARKUS-4942
Quarkus documentation: N/A
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

3.15 aarch64 test plan updates

---

QUARKUS-4210.md

JIRA: https://issues.redhat.com/browse/QUARKUS-4210
Quarkus documentation: https://quarkus.io/version/main/guides/security-ldap#map-ldap-groups-to-securityidentity-roles
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for QUARKUS-4210

---

QUARKUS-5623.md

Add a test plan for QUARKUS-5623
JIRA: https://issues.redhat.com/browse/QUARKUS-5623
Quarkus documentation: https://quarkus.io/version/main/guides/opentelemetry-logging
Extension/feature community status: dev-preview
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add QUARKUS-5623 test plan

---

QUARKUS-3225.md

As we discussed in other PR here: https://github.com/quarkus-qe/quarkus-test-plans/pull/199#issuecomment-2710774192, this PR adds another issue to the FIPS known issues and keeps updating it.

Add another issue related to encrypted PKCS#8 PEM keys not supported on FIPS (QUARKUS-5666)

---

QQE-1450.md

Add test plan for websocket next. There is no quarkus JIRA for the issue yet. If one is created we can rename this TP.
Quarkus documentation: 
https://quarkus.io/version/main/guides/websockets-next-reference
https://quarkus.io/guides/websockets-next-tutorial
Extension/feature community status: stable
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add QQE-1450 test plan

---

QUARKUS-5870.md

JIRA: https://issues.redhat.com/browse/QUARKUS-5870
We got the umbrella JIRA for websocket next. Renaming QQE into QUARKUS designation.

Rename QQE-1450 to QUARKUS-5870

---

QUARKUS-5621.md

JIRA: https://issues.redhat.com/browse/QUARKUS-5621 Quarkus REST - Support record parameter containers
Upstream PRs:
- https://github.com/quarkusio/quarkus/pull/42642
Upstream documentation:
- https://quarkus.io/guides/rest#grouping-parameters-in-a-custom-class
Extension/feature community status: 
- Enhancement for the supported extension
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-5621 Quarkus REST - Support record parameter containers

---

QUARKUS-5611.md

JIRA:
- https://issues.redhat.com/browse/QUARKUS-5611
Upstream PRs:
- https://github.com/quarkusio/quarkus/pull/43609
Extension/feature community status: Enhancement for the supported extension
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for QUARKUS-5611 - Support Keycloak Dev Service when OIDC client is used without OIDC extension

---

QUARKUS-5857.md

JIRA: https://issues.redhat.com/browse/QUARKUS-5857
Upstream PR: https://github.com/quarkusio/quarkus/pull/45809
- Websocket next guide: https://quarkus.io/guides/websockets-next-tutorial
- Websocket next reference: https://quarkus.io/version/main/guides/websockets-next-reference
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for  QUARKUS-5857 

---

QUARKUS-5658.md

* Adding test plan for QUARKUS-5658: OTel - WS.next integration.
JIRA: https://issues.redhat.com/browse/QUARKUS-5658
Quarkus documentation: https://quarkus.io/version/main/guides/websockets-next-reference#telemetry
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-5658: OTel - WS.next integration

---

QUARKUS-5857.md

This is just a small modification from https://github.com/quarkus-qe/quarkus-test-plans/pull/210, removing OCP of the impact resources as it's mentioned here--> https://github.com/quarkus-qe/quarkus-test-suite/pull/2386#issuecomment-2794343641

QUARKUS-5857 Remove OCP from Impact on resources section

---

QUARKUS-5859.md

JIRA: https://issues.redhat.com/browse/QUARKUS-5859
Support permission checkers for WebSockets Next
Upstream PRs:
- https://github.com/quarkusio/quarkus/pull/45704
Upstream documentation:
- https://quarkus.io/guides/websockets-next-reference#secure-endpoints-with-permission-checkers
Extension/feature community status: websockets-next extension is supported in community
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-5859 Support permission checkers for WebSockets Next

---

QUARKUS-5667.md

* Adding test plan for QUARKUS-5667: Integrate Micrometer with WebSockets Next.
JIRA: https://issues.redhat.com/browse/QUARKUS-5667
Quarkus documentation: https://quarkus.io/version/main/guides/websockets-next-reference#telemetry
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-5667: Micrometer - WS.next integration

---

QUARKUS-5622.md

JIRA: https://issues.redhat.com/browse/QUARKUS-5622 
Quarkus documentation:  https://quarkus.io/guides/security-authorize-web-endpoints-reference
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Adding TP for Quarkus-5622 Support @PermissionAllowed for @BeanParam parameter

---

QUARKUS-5668.md

* Adding a test plan for QUARKUS-5668: Integrate Micrometer with WebSockets Next.
Jira: https://issues.redhat.com/browse/QUARKUS-5668
Upstream documentation: https://quarkus.io/guides/opentelemetry-tracing#disabling-traces-for-app-endpoints) 
Code changes:
* https://github.com/quarkusio/quarkus/pull/43885
* https://github.com/quarkusio/quarkus/pull/44724
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Adding QUARKUS-5668 test plan

---

QUARKUS-5866.MD

JIRA: https://issues.redhat.com/browse/QUARKUS-5866
Quarkus documentation: there is no documentation, Quarkus REST client integration with the TLS registry does not mention any limitations, so users were right to expect this to work, even though we present it as a feature
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for QUARKUS-5866

---

QQE-674.md

Add TP related to a fix [#39762](https://github.com/quarkusio/quarkus/pull/39762) to ensure that failed unis are not cached.
Jira fix : https://github.com/quarkusio/quarkus/pull/39762
Jira issue: https://github.com/quarkusio/quarkus/issues/39677
JIRA QQE: https://issues.redhat.com/browse/QQE-674
https://quarkus.io/guides/cache
Extension/feature community status:
https://quarkus.io/extensions/io.quarkus/quarkus-cache/ stable
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add Test Plan for QQE-674

---

QUARKUS-6245.md

JIRA: https://issues.redhat.com/browse/QUARKUS-6245
Quarkus documentation: https://quarkus.io/guides/security-oidc-code-flow-authentication#logout-and-expiration
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-6245 - Allow setting Clear-Site-Data on OIDC logout

---

QUARKUS-6233.md

JIRA: https://issues.redhat.com/browse/QUARKUS-6233
Quarkus documentation: https://quarkus.io/guides/mongodb#tls-configuration
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add TP for QUARKUS-6233 (Allow mongo client to be configured by a tls registry)

---

QUARKUS-6259.md

JIRA: https://issues.redhat.com/browse/QUARKUS-6259
Quarkus documentation: https://quarkus.io/version/main/guides/hibernate-reactive#multiple-persistence-units
Extension/feature community status: fully supported
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-6259 - Enable named data sources for Hibernate Reactive

---

QUARKUS-5881.MD

JIRA: https://issues.redhat.com/browse/QUARKUS-5881
Quarkus documentation: https://quarkus.io/guides/all-config#quarkus-agroal_quarkus-datasource-jdbc-validation-query-timeout
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plan for QUARKUS-5881- Datasource is too slow to recover when a DB failover occurs

---

QUARKUS-6264.md

JIRA: https://issues.redhat.com/browse/QUARKUS-6264
Quarkus documentation: none
Extension/feature community status: full support
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

QUARKUS-6264 - bump kafka clients to 4.0.0

---

QUARKUS-6292.md
QUARKUS-6293.md
QUARKUS-6397.md

JIRA: https://issues.redhat.com/browse/QUARKUS-6292
JIRA: https://issues.redhat.com/browse/QUARKUS-6293
JIRA: https://issues.redhat.com/browse/QUARKUS-6397
Quarkus documentation: Not for all the features in this epic only the CLI
- https://quarkus.io/guides/extension-metadata#extension-offerings
- https://quarkus.io/guides/extension-registry-user#limiting-extension-catalog-to-an-offering
Extension/feature community status: N/A not specific extension
Adding the TP for feature https://issues.redhat.com/browse/QUARKUS-6292 which contains sub tasks.
These sub task should have separate TP and they should be linked to TP for https://issues.redhat.com/browse/QUARKUS-6292
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add feature test plan for QUARKUS-6292 (Extend the platform with offering) with child test plans

---

QUARKUS-6471.md

JIRA:  https://issues.redhat.com/browse/QUARKUS-6471
Quarkus documentation: https://quarkus.io/guides/security-oidc-expanded-configuration#resource-metadata-properties
Extension/feature community status: full-support for extension, so, I suppose, the feature is also fully supported
- Logging
- Tracing
- Metrics
- Security
- OpenAPI
- Data sources
- Frontend
- Qute

Add test plans for OAuth2 Protected Resource Metadata(QUARKUS-6471)
